export enum PerkType {
    FREE_WATER = "FREE_WATER",
    TOILET = "TOILET",
    STREET_TERRACE = "STREET_TERRACE",
    CHARGER = "CHARGER",
    VEGETARIAN = "VEGETARIAN",
    TOPPINGS = "TOPPINGS",
    SOCKET = "SOCKET",
    GRAIN_COFFEE = "GRAIN_COFFEE",
    WIFI = "WIFI"
}